### ISSUE TITLE
utxo_amtpercent

### ISSUE THREAD

**Issue by AdamISZ** [kristapsk/bitcoin-scripts#1]
Re this: https://github.com/kristapsk/bitcoin-scripts/blob/master/fake-coinjoin.sh#L19

Just to mention, it's not a lower limit on the amount of utxos you can use in the coinjoin; it's only a lower limit on the specific utxo that's used to create a "podle" token, the thing that rate limits takers. That utxo is usually one of the ones that are inputs to the coinjoin, but doesn't have to be. Anyway, details, but there are no limits on the sizes of utxos that either makers or takers use for input.

**Comment by kristapsk** [comment]
Ok, thanks for feedback. Probably I need to look more at the JM code. But if I understand correctly, I could just simply remove that utxo_amtpercent variable and all related checks from my script?

**Comment by AdamISZ** [comment]
Yup. I'll take another look shortly and see if there's anything else that might need to be added/removed to fit the "consensus rules" of JM.
