### ISSUE TITLE
Ricochet should randomize tx fees for individual transactions

### ISSUE THREAD

**Issue by kristapsk** [kristapsk/bitcoin-scripts#11]
https://www.reddit.com/r/Bitcoin/comments/8x6v7z/is_this_how_samourai_wallet_ricochet_transactions/e221u3p/

**Comment by openoms** [comment]
and split the amount to two so it does not look like a chain of self-tansfers

**Comment by kristapsk** [comment]
That's more complicated and different issue. Samourai sends second output to themselves, as a fee for using service.

**Comment by openoms** [comment]
You are right it does not seem like that apart from paying the fee it would create any other outputs to split the transactions:
https://docs.samourai.io/en/spend-tools
![image](https://user-images.githubusercontent.com/43343391/132301104-d480a113-c038-4802-a95f-52b552c415de.png)

There is contradicting info on reddit though, but from 3 years ago:
https://www.reddit.com/r/Bitcoin/comments/8x6v7z/is_this_how_samourai_wallet_ricochet_transactions/e21icph/?context=8&depth=9
![image](https://user-images.githubusercontent.com/43343391/132301023-063aff35-aa07-458d-8658-d9491da9b5ad.png)

**Comment by kristapsk** [comment]
Implemented in c4a40e01f439e7dbafa0a5a3aa7383794012e3e2
