### ISSUE TITLE
How can I get the script I just copy and paste to blockchain console to change address of unconfirmed transactions

### ISSUE THREAD

**Issue by Chigopen** [kristapsk/bitcoin-scripts#19]

**Comment by kristapsk** [comment]
Sorry, missed this. But I'm not sure I really understand the problem....

**Comment by kristapsk** [comment]
You mean - how to double spend unconfirmed tx?

**Comment by Chigopen** [comment]
Yes I need the script pls I have tried so many times in console but not working
