### ISSUE TITLE
problem running "ricochet-send.sh

### ISSUE THREAD

**Issue by pgpric** [kristapsk/bitcoin-scripts#21]
./inc.common.sh: line 57: bitcoin-cli: command not found
./inc.common.sh: line 219: jq: command not found
./inc.common.sh: line 57: bitcoin-cli: command not found

**Comment by kristapsk** [comment]
It looks you don't have necessary dependencies installed, both bitcoin-cli and jq are required, see README.

**Comment by kristapsk** [comment]
@pgpric Did you managed to solve this issue for yourself?

**Comment by pgpric** [comment]
not

**Comment by pgpric** [comment]
@kristapsk it is bitcoin core what you have to download.!

**Comment by kristapsk** [comment]
> @kristapsk it is bitcoin core what you have to download.!

Yes, Bitcoin full node (bitcoind or bitcoin-qt) is requirement for most of these scripts.

**Comment by pgpric** [comment]
thanks

**Comment by pgpric** [comment]
with this I can make bitcoin transfers.!

**Comment by kristapsk** [comment]
@pgpric Did you managed to solve your issues and this can be closed?
