### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by CoreLine76** [kristapsk/bitcoin-scripts#23]
I'm done so far. But now I am getting such error. Could you help.
dostum@ubuntu:~/bitcoin-scripts$ ./ricochet-send.sh 0.999 bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 5 $(./estimatesmartfee.sh $(./timetoblocks.sh "24 hours"))
(standard_in) 1: syntax error
(standard_in) 1: syntax error
./inc.common.sh: line 189: ((: ,00000000             <         ,00001000     : syntax error: operand expected (error token is ",00000000             <         ,00001000     ")
(standard_in) 1: syntax error
Ricocheting 0.999 BTC to bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 via 5 hops using average  fee per kvB
Is this ok? 

dostum@ubuntu:~/bitcoin-scripts$ ./fake-coinjoin.sh $(./randbtc.sh 0.001 0.002) bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 bc1qwfafhs3ztp5d78n3jwwvlel0m7g0njj949zdya
(standard_in) 1: syntax error
Usage: fake-coinjoin.sh [options] amount address1 address2...
Where:
  amount              - amount to send in BTC
  address...          - destination addresses (2 or more)
dostum@ubuntu:~/bitcoin-scripts$

**Comment by kristapsk** [comment]
Sounds like a locale related issue. Could you try `$ bash -x ./ricochet-send.sh 0.999 bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 5`, it will give more debug output?

**Comment by CoreLine76** [comment]
> Sounds like a locale related issue. Could you try `$ bash -x ./ricochet-send.sh 0.999 bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 5`, it will give more debug output?

dostum@ubuntu:~/bitcoin-scripts$ bash -x ./ricochet-send.sh 0.999 bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 5
++ dirname ./ricochet-send.sh
+ . ./inc.common.sh
++ bitcoin_cli=bitcoin-cli
++ bitcoin_cli_options=
++ testnet=0
++ ((  3 > 0  ))
++ [[ 0 == \- ]]
++ bitcoin_cli=bitcoin-cli
++ TX_INPUTS_MAX=253
++ TX_OUTPUTS_MAX=253
++ TX_FIXED_SIZE=10
++ TX_SEGWIT_FIXED_SIZE=11
++ TX_P2PKH_IN_SIZE=148
++ TX_P2PKH_OUT_SIZE=34
++ TX_P2SH_SEGWIT_IN_SIZE=91
++ TX_P2SH_OUT_SIZE=32
++ TX_P2WPKH_IN_SIZE=69
++ TX_P2WPKH_OUT_SIZE=31
++ MAINNET_ADDRESS_REGEX='\([13][a-km-zA-HJ-NP-Z1-9]\{25,39\}\|bc1[qpzry9x8gf2tvdw0s][ac-hi-np-z02-9]\{7,86\}\|BC1[QPZRY9X8GF2TVDW0S][AC-HI-NP-Z02-9]\{7,86\}\)'
++ TESTNET_ADDRESS_REGEX='\([mn2][a-km-zA-HJ-NP-Z1-9]\{25,39\}\|\(bcrt1\|tb1\)[qpzry9x8gf2tvdw0s][ac-hi-np-z02-9]\{7,86\}\|TB1[QPZRY9X8GF2TVDW0S][AC-HI-NP-Z02-9]\{7,86\}\)'
+ '[' bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 == '' ']'
+ check_multiwallet
+ call_bitcoin_cli getwalletinfo
+ bitcoin-cli getwalletinfo
error code: -28
error message:
Verifying blocks…
+ kill 2896
Terminated

**Comment by kristapsk** [comment]
> * error code: -28
>   error message:
>   Verifying blocks…

That's different error than above. Here you ran the script before Bitcoin Core has finished loading.

**Comment by CoreLine76** [comment]
> > * hata kodu: -28 hata iletisi: Blokları doğrulama…
> 
> Bu yukarıdakinden farklı bir hata. Burada Bitcoin Core yüklenmeyi bitirmeden önce betiği çalıştırdınız.

dostum@ubuntu:~/bitcoin-scripts$ bash -x ./ricochet-send.sh 0.999 bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 5
++ dirname ./ricochet-send.sh
+ . ./inc.common.sh
++ bitcoin_cli=bitcoin-cli
++ bitcoin_cli_options=
++ testnet=0
++ ((  3 > 0  ))
++ [[ 0 == \- ]]
++ bitcoin_cli=bitcoin-cli
++ TX_INPUTS_MAX=253
++ TX_OUTPUTS_MAX=253
++ TX_FIXED_SIZE=10
++ TX_SEGWIT_FIXED_SIZE=11
++ TX_P2PKH_IN_SIZE=148
++ TX_P2PKH_OUT_SIZE=34
++ TX_P2SH_SEGWIT_IN_SIZE=91
++ TX_P2SH_OUT_SIZE=32
++ TX_P2WPKH_IN_SIZE=69
++ TX_P2WPKH_OUT_SIZE=31
++ MAINNET_ADDRESS_REGEX='\([13][a-km-zA-HJ-NP-Z1-9]\{25,39\}\|bc1[qpzry9x8gf2tvdw0s][ac-hi-np-z02-9]\{7,86\}\|BC1[QPZRY9X8GF2TVDW0S][AC-HI-NP-Z02-9]\{7,86\}\)'
++ TESTNET_ADDRESS_REGEX='\([mn2][a-km-zA-HJ-NP-Z1-9]\{25,39\}\|\(bcrt1\|tb1\)[qpzry9x8gf2tvdw0s][ac-hi-np-z02-9]\{7,86\}\|TB1[QPZRY9X8GF2TVDW0S][AC-HI-NP-Z02-9]\{7,86\}\)'
+ '[' bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 == '' ']'
+ check_multiwallet
+ call_bitcoin_cli getwalletinfo
+ bitcoin-cli getwalletinfo
+ amount=0.999
+ address=bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83
+ is_valid_bitcoin_address bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83
+ '[' 0 == 1 ']'
+ LANG=POSIX
+ grep -qse '^\([13][a-km-zA-HJ-NP-Z1-9]\{25,39\}\|bc1[qpzry9x8gf2tvdw0s][ac-hi-np-z02-9]\{7,86\}\|BC1[QPZRY9X8GF2TVDW0S][AC-HI-NP-Z02-9]\{7,86\}\)$'
+ return 0
+ hops=5
+ sleeptime_min=10
+ sleeptime_max=15
+ '[' 5 '!=' '' ']'
+ hops=5
+ '[' '' '!=' '' ']'
+++ dirname ./ricochet-send.sh
++ ./estimatesmartfee.sh 2
+ txfee=0,00000000
+ '[' '' '!=' '' ']'
+ '[' '' '!=' '' ']'
+ '[' '' '!=' '' ']'
+ hop_confirmations=0
+ '[' '' '!=' '' ']'
+ txfee_factor=0.3
++ bc_float_calc '0,00000000 * (1 - 0.3)'
++ echo 'scale=8; 0,00000000 * (1 - 0.3)'
++ btc_amount_format
++ awk '{ print sprintf("%.8f", $1); }'
++ bc
(standard_in) 1: syntax error
+ txfee_min=
++ bc_float_calc '0,00000000 * (1 + 0.3)'
++ echo 'scale=8; 0,00000000 * (1 + 0.3)'
++ bc
++ btc_amount_format
++ awk '{ print sprintf("%.8f", $1); }'
(standard_in) 1: syntax error
+ txfee_max=
++ call_bitcoin_cli getmempoolinfo
++ bitcoin-cli getmempoolinfo
++ jq_btc_float .mempoolminfee
++ jq .mempoolminfee
++ btc_amount_format
++ awk '{ print sprintf("%.8f", $1); }'
+ mempoolminfee=0,00001000
+ is_btc_lt '' 0,00001000
++ echo ''
++ btc_amount_format
++ awk '{ print sprintf("%.8f", $1); }'
++ tr -d .
++ sed 's/^$/0/'
++ sed 's/^0*//'
++ echo 0,00001000
++ tr -d .
++ sed 's/^$/0/'
++ sed 's/^0*//'
++ btc_amount_format
++ awk '{ print sprintf("%.8f", $1); }'
+ ((          ,00000000             <         ,00001000      ))
./inc.common.sh: line 189: ((: ,00000000             <         ,00001000     : syntax error: operand expected (error token is ",00000000             <         ,00001000     ")
++ bc_float_calc '( + ) * 0.5'
++ echo 'scale=8; ( + ) * 0.5'
++ bc
(standard_in) 1: syntax error
++ btc_amount_format
++ awk '{ print sprintf("%.8f", $1); }'
+ txfee_average=
+ echo 'Ricocheting 0.999 BTC to bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 via 5 hops using average  fee per kvB'
Ricocheting 0.999 BTC to bc1qxhq2vpzy0ne9wwu76z9kljyesewq56ax3nvw83 via 5 hops using average  fee per kvB
+ read -p 'Is this ok? ' -n 1 -r
Is this ok? 
+ echo

+ [[ '' =~ ^[Yy]$ ]]
+ exit

**Comment by kristapsk** [comment]
What is your locale? Could you run `echo $LANG` and paste output here? If my theory is correct, that should allow me to reproduce your issue on my machine if I know your locale setting.

**Comment by kristapsk** [comment]
> > echo $LANG
> > en_US.UTF-8

Then it's something else, `en_US.UTF-8` definitely should be ok... :(

**Comment by kristapsk** [comment]
> * txfee=0,00000000

It looks problem is here, Bitcoin Core RPC on your machine returns values with comma as a decimal separator and later `bc` does no like that. Will look how to properly fix this.

**Comment by kristapsk** [comment]
Or, actually it's likely `btc_amount_format` function from `inc.common.sh`, which uses `awk`, that changes from point to comma.

**Comment by kristapsk** [comment]
@CoreLine76 Could you also run `bash -x estimatesmartfee.sh 2` and also `bitcoin-cli estimatesmartfee 2` manually and paste outputs here? That should give me enough information to know for sure where is the problem.

**Comment by CoreLine76** [comment]
dostum@ubuntu:~/bitcoin-scripts$ bash -x estimatesmartfee.sh
++ dirname estimatesmartfee.sh
+ . ./inc.common.sh
++ bitcoin_cli=bitcoin-cli
++ bitcoin_cli_options=
++ testnet=0
++ ((  0 > 0  ))
++ bitcoin_cli=bitcoin-cli
++ TX_INPUTS_MAX=253
++ TX_OUTPUTS_MAX=253
++ TX_FIXED_SIZE=10
++ TX_SEGWIT_FIXED_SIZE=11
++ TX_P2PKH_IN_SIZE=148
++ TX_P2PKH_OUT_SIZE=34
++ TX_P2SH_SEGWIT_IN_SIZE=91
++ TX_P2SH_OUT_SIZE=32
++ TX_P2WPKH_IN_SIZE=69
++ TX_P2WPKH_OUT_SIZE=31
++ MAINNET_ADDRESS_REGEX='\([13][a-km-zA-HJ-NP-Z1-9]\{25,39\}\|bc1[qpzry9x8gf2tvdw0s][ac-hi-np-z02-9]\{7,86\}\|BC1[QPZRY9X8GF2TVDW0S][AC-HI-NP-Z02-9]\{7,86\}\)'
++ TESTNET_ADDRESS_REGEX='\([mn2][a-km-zA-HJ-NP-Z1-9]\{25,39\}\|\(bcrt1\|tb1\)[qpzry9x8gf2tvdw0s][ac-hi-np-z02-9]\{7,86\}\|TB1[QPZRY9X8GF2TVDW0S][AC-HI-NP-Z02-9]\{7,86\}\)'
+ '[' '' == '' ']'
++ basename estimatesmartfee.sh
+ echo 'Usage: estimatesmartfee.sh [options] blocks'
Usage: estimatesmartfee.sh [options] blocks
+ exit 0
dostum@ubuntu:~/bitcoin-scripts$ bitcoin-cli estimatesmartfee 2
{
  "errors": [
    "Insufficient data or no feerate found"
  ],
  "blocks": 0
}
dostum@ubuntu:~/bitcoin-scripts$

**Comment by CoreLine76** [comment]
This problem is not related to your software. I think it is completely related to my local ubuntu software. Your codes are working fine on the remote machine.

**Comment by CoreLine76** [comment]
root@localhost:/home/bitcoin-scripts-master# ./fake-coinjoin.sh $(./randbtc.sh 0.900 0.999) bc1q7eqheemcu6xpgr42vl0ayel6wj087nxdfjfndf bc1qnjq9demnmud92gxh2mdefrzseatzflmewapnv5
Feerate 0.00000916 is below minimum mempool fee, raising to 0.00001000
Using fee 0.00001000 per KB
Recipients: bc1q7eqheemcu6xpgr42vl0ayel6wj087nxdfjfndf bc1qnjq9demnmud92gxh2mdefrzseatzflmewapnv5
input_type: bech32
Selected maker inputs:
Calculated maker outputs:
Not enough good inputs, aborting.
root@localhost:/home/bitcoin-scripts-master#
------------------------------------------------------------------------------------
root@localhost:/home/bitcoin-scripts-master# ./ricochet-send.sh 0.999 bc1qnjq9demnmud92gxh2mdefrzseatzflmewapnv5 5 $(./estimatesmartfee.sh $(./timetoblocks.sh "24 hours"))
Feerate 0.00000700 is below minimum mempool fee, raising minimum to 0.00001000
Ricocheting 0.999 BTC to bc1qnjq9demnmud92gxh2mdefrzseatzflmewapnv5 via 5 hops using average 0.00001150 fee per kvB
Is this ok?

root@localhost:/home/bitcoin-scripts-master#

**Comment by CoreLine76** [comment]
thanks. please ticket off

**Comment by CoreLine76** [comment]
The problem was not in your software. The problem was in the ubuntu library. I removed all components. I updated and upgraded from scratch. I added the ubuntu keys again. In short, I reinstalled everything and requirements. It worked. Now I'm installing it on the remote machine.

**Comment by CoreLine76** [comment]
Thank you for your help. now the only problem is to be able to send fake btc. I'm sending, but when I query the wallet on the blockchain, it doesn't seem to have gone.

**Comment by CoreLine76** [comment]
Dear @kristapsk you can close the ticket. I will create a new ticket. About sending fake btc. Thank you very much again.
