### ISSUE TITLE
Why is it not visible on the blockchain network? Or what is the error?

### ISSUE THREAD

**Issue by CoreLine76** [kristapsk/bitcoin-scripts#24]
How can I see the flash btc I have sent on the blockchain network? It doesn't seem to be gone when I checked. or am i doing it wrong. my master

root@u22413795:/home/bitc/bitcoin-scripts# ./ricochet-send.sh 0.001 bc1q... 5 $(./estimatesmartfee.sh $(./timetoblocks.sh "24 hours"))
Feerate 0.00000700 is below minimum mempool fee, raising minimum to 0.00001000
Ricocheting 0.001 BTC to bc1qy33egseydyxxt3uj6gpqqxewt0 via 5 hops using average 0.00001150 fee per kvB
Is this ok?

root@u22413795:/home/bitc/bitcoin-scripts# ./fake-coinjoin.sh $(./randbtc.sh 0.900 0.999) bc1qwfafhs3ztp5d78n3jwwvlel0m7g0
Feerate 0.00000942 is below minimum mempool fee, raising to 0.00001000
Using fee 0.00001000 per KB
Recipients: bc1qwfafhs3ztp5d78n3jwwvlel0m
input_type: bech32
Selected maker inputs:
Calculated maker outputs:
Not enough good inputs, aborting.
root@u22413795:/home/bitc/bitcoin-scripts#

**Comment by CoreLine76** [comment]
root@u22413795:~/.bitcoin/wallets# bitcoin-cli listunspent 1 999999
[
]
root@u22413795:~/.bitcoin/wallets#

**Comment by CoreLine76** [comment]
my dear master. First of all, thank you for your warning. I guess we'll have to download all the hass of btc before we fake it, is it true? a total of 500 gb of data in total. I had to buy a 2 terabyte server for this.
I hope I am not wrong.

**Comment by CoreLine76** [comment]
> You can check available confirmed UTXOs in your wallet with `bitcoin-cli listunspent 1 999999`.

hello my master @kristapsk 

root@ubuntu:/home/bitcore/bitcoin-scripts# bitcoin-cli listunspent 1 999999
[
]
root@ubuntu:/home/bitcore/bitcoin-scripts#

**Comment by kristapsk** [comment]
>  I guess we'll have to download all the hass of btc before we fake it, is it true?

I'm not sure I understand what are you trying to achive. These scripts do not create "fake bitcoins".

**Comment by CoreLine76** [comment]
For days I thought Flash bitcoin was sent via testnet.

**Comment by CoreLine76** [comment]
thank you @kristapsk 
please closed ticket
