### ISSUE TITLE
bitcoin-cli listunspent 0 9999 error

### ISSUE THREAD

**Issue by CoreLine76** [kristapsk/bitcoin-scripts#25]
root@ubuntu:~/.bitcoin# bitcoin-cli listunspent 0 9999
[
]
I don't know what to fix here. Can you describe my master to me?

**Comment by CoreLine76** [comment]
@kristapsk 
I don't know where I went wrong. I have pulled all the data of bitcoin since 2009. In the /root/.bitcoin directory. bitcoin/script is in the /home directory. I'm writing the code you said and the parenthesis sign appears. I really don't know what to do. Can you help me. what am i missing? I don't know.

**Comment by kristapsk** [comment]
You must have bitcoins in your wallet to use scripts that create transactions. You don't have any.

**Comment by CoreLine76** [comment]
btc how much should it be minimum. This is exactly what's happening. i will add btc to my wallet. Let's say I threw 0.001 btc. With this btc, can I send as many btc as I want as fake?

**Comment by kristapsk** [comment]
> can I send as many btc as I want as fake?

You don't fake BTC with these scripts. That's impossible to do.

**Comment by CoreLine76** [comment]
please ticket closed. thanks
