### ISSUE TITLE
fake conjoin 

### ISSUE THREAD

**Issue by roses2w** [kristapsk/bitcoin-scripts#32]
I go to use, i paste in cmd, immediately disappears and closes cmd
any idea why

**Comment by kristapsk** [comment]
Operating system? You run command from some GUI command? You should run it from terminal, without arguments it will output usage info and terminate.

**Comment by roses2w** [comment]
OK
now, i placed in CMD it immediately closes like -so fast i do not see it happen
i placed in python  opens a says many errors

I am working on it - as i would like one to move my btc as stuck and i wish to use to help people in the cold as quick as possible

Would you be of further assistance later please with a few questions
as i am just stupid - i can do some = not all of it

thank you though for answering


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by roses2w** [comment]
Mr Mike- stated about the meteorites coming and other aspects as per temple and pyramids to be seen
also as per children not being around

so is this what is happening

the vaccine has lower those who took it - to point of AIDS in military and deaths every where plus the cancer from almost anything

so if everyone has, and they can track, those with the vaccine through blue tooth

the radiation in from atmosphere deaths and the lack of children and
deaths - is it to 1 lower population so to handle after a the asteroids and problems with atmosphere or
to cause so many deaths and heart ache so no thinks of it
or
a human sacrifice for new world order?


  1.   https://healthrangerreport.com/situation-update-mar-6-2023-bombshell-leaked-govt-messages-reveal-covid-was-a-planned-psychological-terrorism-campaign-from-the-very-start
[http://assets.libsyn.com/show/74593?height=250&width=250&overlay=true]<https://healthrangerreport.com/situation-update-mar-6-2023-bombshell-leaked-govt-messages-reveal-covid-was-a-planned-psychological-terrorism-campaign-from-the-very-start>
The Health Ranger Report: Situation Update, Mar 6, 2023 - BOMBSHELL: Leaked govt. messages reveal COVID was a planned psychological terrorism campaign from the very start<https://healthrangerreport.com/situation-update-mar-6-2023-bombshell-leaked-govt-messages-reveal-covid-was-a-planned-psychological-terrorism-campaign-from-the-very-start>
healthrangerreport.com
https://www.infowars.com/posts/powerful-report-bill-gates-next-big-pandemic-to-target-children/
