### ISSUE TITLE
Obtain whitepaper from the UTXO set, allowing compatibility with pruning

### ISSUE THREAD

**Issue by chris-belcher** [kristapsk/bitcoin-scripts#9]
I was reading `whitepaper.sh` and the stackexchange thread, and noticed that the whitepaper is encoded in old-style multisig outputs.

That means it's stored in the UTXO set, and accessible to nodes even if they enable pruning.

They should be accessible using RPC calls `gettxout 54e48e5f5c656b26c3bca14a8c95aa583d07ebe84dde3b7dd4a78f4e4186e713 <index 0-947>`

**Comment by kristapsk** [comment]
Oh, right, nice catch! Will look into it.

**Comment by nopara73** [comment]
Let's hope CSW won't notice your copyright infringement on his Bitcoin whitepaper 🤞 😄

**Comment by chris-belcher** [comment]
Well done @jb55 for coding it up first!

https://bitcoinhackers.org/@jb55/105595146491662406

**Comment by kristapsk** [comment]
@chris-belcher Started writing comment about this, but you were first. :) It's cool oneliner, but compared to my solution it's slow - more than 15 seconds vs less than 2 seconds in my tests. But that's I guess is 1 RPC vs 948 RPC's. In any case, copying it here too, if bitcoinhackers.org goes down in the future.
```
seq 0 947 | (while read -r n; do bitcoin-cli gettxout 54e48e5f5c656b26c3bca14a8c95aa583d07ebe84dde3b7dd4a78f4e4186e713 $n | jq -r '.scriptPubKey.asm' | awk '{ print $2 $3 $4 }'; done) | tr -d '\n' | cut -c 17-368600 | xxd -r -p > bitcoin-test.pdf
```

**Comment by jb55** [comment]
Kristaps Kaupe <notifications@github.com> writes:
> @chris-belcher Started writing comment about this, but you were first.
> :) It's cool oneliner, but compared to my solution it's slow - more
> than 15 seconds vs less than 2 seconds in my tests. But that's I guess
> is 1 RPC vs 948 RPC's. In any case, copying it here too, if
> bitcoinhackers.org goes down in the future.

I considered making a jsonrpc version with curl (I do this for my
personal scripts) but went with this since not everyone has rpc enabled.
A jsonrpc curl one liner would be interesting... ahhh I'm getting nerd
sniped again. back to work.

**Comment by kristapsk** [comment]
@jb55 , didn't get your comment - `bitcoin-cli` is just another way to call JSON-RPC, it will not work without RPC enabled.

**Comment by jb55** [comment]
Kristaps Kaupe <notifications@github.com> writes:
> @jb55 , didn't get your comment - `bitcoin-cli` is just another way to
> call JSON-RPC, it will not work without RPC enabled.

@kristapsk To do batch jsonrpc with curl you need credentials (cookie or
user/pass config) so it wouldn't be simple one-liner like the cli
version was my only point. This is what I meant by enabled (user/pass
set). Not sure how to detect and do jsonrpc cookie auth with curl...
